# Generated by Django 2.2.6 on 2019-10-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=254)),
                ('credit_card_number', models.CharField(max_length=254, unique=True)),
                ('cvv_number', models.IntegerField()),
                ('expiration_year', models.IntegerField()),
                ('expiration_month', models.IntegerField()),
            ],
        ),
    ]
